[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B"]
ignore = []
exclude = ["mlruns"]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["qdrant_client", "sentence_transformers", "sentence_transformers.*"]
ignore_missing_imports = true
